"""
Generated from symbols.json for ::java::data::dialog::action::ClickAction
Local link to file: generated_symbols/data/dialog/action/ClickAction.py
"""
# ~~~ CODE ~~~
from dataclasses import dataclass
from typing import TYPE_CHECKING, Annotated, Any, Literal

from minecraft_registry import IdSpec

if TYPE_CHECKING:
    from generated_symbols.data.dialog.Dialog import Dialog
    from generated_symbols.registry.KnownDialogId import KnownDialogId
    from generated_symbols.util.custom_event.UnknownDynamicAdditions import UnknownDynamicAdditions


@dataclass(kw_only=True)
class ClickActionChangePage:
    type: Literal['minecraft:change_page']
    page: Annotated[int, 'Range | `1` and above | inclusive']  # The page number to go to.


@dataclass(kw_only=True)
class ClickActionCopyToClipboard:
    type: Literal['minecraft:copy_to_clipboard']
    value: str  # The text value to copy to the clipboard.


@dataclass(kw_only=True)
class ClickActionCustom:
    type: Literal['minecraft:custom']
    id: Annotated[str, IdSpec()]  # ID of a custom action. Has no functionality on vanilla servers.
    payload: Any | None = None


@dataclass(kw_only=True)
class ClickActionDynamicCustom:
    type: Literal['minecraft:dynamic/custom']
    id: Annotated[str, IdSpec()]  # ID of a custom action. Has no functionality on vanilla servers.
    additions: UnknownDynamicAdditions | None = None  # Static fields added in addition to the fields generated by input.


@dataclass(kw_only=True)
class ClickActionDynamicRunCommand:
    type: Literal['minecraft:dynamic/run_command']
    template: str  # A macro template to be interpred as a command. Special characters (including both `'` and `"`) from text input will be escaped to fit in SNBT literal.


@dataclass(kw_only=True)
class ClickActionOpenUrl:
    type: Literal['minecraft:open_url']
    url: str


@dataclass(kw_only=True)
class ClickActionRunCommand:
    type: Literal['minecraft:run_command']
    command: str


@dataclass(kw_only=True)
class ClickActionShowDialog:
    type: Literal['minecraft:show_dialog']
    dialog: Annotated[str, IdSpec(registry='dialog')] | KnownDialogId | Dialog


@dataclass(kw_only=True)
class ClickActionSuggestCommand:
    type: Literal['minecraft:suggest_command']
    command: str


type ClickAction = ClickActionChangePage | ClickActionCopyToClipboard | ClickActionCustom | ClickActionDynamicCustom | ClickActionDynamicRunCommand | ClickActionOpenUrl | ClickActionRunCommand | ClickActionShowDialog | ClickActionSuggestCommand


# ~~~ MODEL DUMP ~~~
_ = {
    "::java::data::dialog::action::ClickAction": {
        "kind": "struct",
        "fields": [
            {
                "kind": "pair",
                "key": "type",
                "type": {
                    "kind": "string",
                    "attributes": [
                        {
                            "name": "id",
                            "value": {
                                "kind": "literal",
                                "value": {
                                    "kind": "string",
                                    "value": "dialog_action_type"
                                }
                            }
                        }
                    ]
                }
            },
            {
                "kind": "spread",
                "type": {
                    "kind": "dispatcher",
                    "parallelIndices": [
                        {
                            "kind": "dynamic",
                            "accessor": [
                                "type"
                            ]
                        }
                    ],
                    "registry": "minecraft:dialog_action"
                }
            }
        ]
    }
}

