"""
Generated from symbols.json for ::java::data::dialog::action::DynamicCustomAction
Local link to file: generated_symbols/data/dialog/action/DynamicCustomAction.py
"""
# ~~~ CODE ~~~
from dataclasses import dataclass
from typing import TYPE_CHECKING, Annotated

from runtime_metadata import IdSpec

if TYPE_CHECKING:
    from generated_symbols.util.custom_event.UnknownDynamicAdditions import UnknownDynamicAdditions


@dataclass(kw_only=True)
class DynamicCustomAction:
    id: Annotated[str, IdSpec()]  # ID of a custom action. Has no functionality on vanilla servers.
    additions: UnknownDynamicAdditions | None = None  # Static fields added in addition to the fields generated by input.


# ~~~ MODEL DUMP ~~~
_ = {
    "::java::data::dialog::action::DynamicCustomAction": {
        "kind": "struct",
        "fields": [
            {
                "kind": "pair",
                "desc": "ID of a custom action.\nHas no functionality on vanilla servers.",
                "key": "id",
                "type": {
                    "kind": "string",
                    "attributes": [
                        {
                            "name": "id"
                        },
                        {
                            "name": "dispatcher_key",
                            "value": {
                                "kind": "literal",
                                "value": {
                                    "kind": "string",
                                    "value": "mcdoc:custom_dynamic_event_additions"
                                }
                            }
                        }
                    ]
                }
            },
            {
                "kind": "pair",
                "desc": "Static fields added in addition to the fields generated by input.",
                "key": "additions",
                "type": {
                    "kind": "dispatcher",
                    "parallelIndices": [
                        {
                            "kind": "dynamic",
                            "accessor": [
                                "id"
                            ]
                        }
                    ],
                    "registry": "mcdoc:custom_dynamic_event_additions"
                },
                "optional": True
            }
        ]
    }
}

