"""
Generated from symbols.json for ::java::util::text::Keybind
Local link to file: vanilla_mcdoc/util/text/Keybind.py
"""
# ~~~ CODE ~~~
from enum import StrEnum


class Keybind(StrEnum):
    ADVANCEMENTS = "key.advancements"
    ATTACK = "key.attack"
    BACK = "key.back"
    CHAT = "key.chat"
    COMMAND = "key.command"
    DEBUGCLEARCHAT = "key.debug.clearChat"
    DEBUGCOPYLOCATION = "key.debug.copyLocation"
    DEBUGCOPYRECREATECOMMAND = "key.debug.copyRecreateCommand"
    DEBUGCRASH = "key.debug.crash"
    DEBUGOPTIONSMENU = "key.debug.debugOptions"
    DEBUGDUMPDYNAMICTEXTURES = "key.debug.dumpDynamicTextures"
    DEBUGDUMPVERSION = "key.debug.dumpVersion"
    DEBUGFOCUSPAUSE = "key.debug.focusPause"
    DEBUGFPSCHARTS = "key.debug.fpsCharts"
    DEBUGIMPROVEDTRANSPARENCY = "key.debug.improvedTransparency"
    DEBUGLIGHTMAPTEXTURE = "key.debug.lightmapTexture"
    DEBUGMODIFIER = "key.debug.modifier"
    DEBUGNETWORKCHARTS = "key.debug.networkCharts"
    DEBUGOVERLAY = "key.debug.overlay"
    DEBUGPROFILING = "key.debug.profiling"
    DEBUGPROFILINGCHART = "key.debug.profilingChart"
    DEBUGRELOADCHUNK = "key.debug.reloadChunk"
    DEBUGRELOADRESOURCEPACKS = "key.debug.reloadResourcePacks"
    DEBUGSHOWADVANCEDTOOLTIPS = "key.debug.showAdvancedTooltips"
    DEBUGSHOWCHUNKBORDERS = "key.debug.showChunkBorders"
    DEBUGSHOWHITBOXES = "key.debug.showHitboxes"
    DEBUGSPECTATE = "key.debug.spectate"
    DEBUGSWITCHGAMEMODE = "key.debug.switchGameMode"
    DROP = "key.drop"
    FORWARD = "key.forward"
    FRIENDS = "key.friends"
    FULLSCREEN = "key.fullscreen"
    HOTBAR1 = "key.hotbar.1"
    HOTBAR2 = "key.hotbar.2"
    HOTBAR3 = "key.hotbar.3"
    HOTBAR4 = "key.hotbar.4"
    HOTBAR5 = "key.hotbar.5"
    HOTBAR6 = "key.hotbar.6"
    HOTBAR7 = "key.hotbar.7"
    HOTBAR8 = "key.hotbar.8"
    HOTBAR9 = "key.hotbar.9"
    INVENTORY = "key.inventory"
    JUMP = "key.jump"
    LEFT = "key.left"
    LOADTOOLBARACTIVATOR = "key.loadToolbarActivator"
    PICKITEM = "key.pickItem"
    PLAYERLIST = "key.playerlist"
    QUICKACTIONS = "key.quickActions"
    RIGHT = "key.right"
    SAVETOOLBARACTIVATOR = "key.saveToolbarActivator"
    SCREENSHOT = "key.screenshot"
    SMOOTHCAMERA = "key.smoothCamera"
    SNEAK = "key.sneak"
    SPECTATORHOTBAR = "key.spectatorHotbar"
    SPECTATOROUTLINES = "key.spectatorOutlines"
    SPRINT = "key.sprint"
    SWAPOFFHAND = "key.swapOffhand"
    TOGGLEGUI = "key.toggleGui"
    TOGGLEPERSPECTIVE = "key.togglePerspective"
    TOGGLESPECTATORSHADEREFFECTS = "key.toggleSpectatorShaderEffects"
    USE = "key.use"
