"""
Generated from symbols.json for ::java::world::entity::mob::breedable::horse::HorseVariantAndMarkings
Local link to file: vanilla_mcdoc/world/entity/mob/breedable/horse/HorseVariantAndMarkings.py
"""
# ~~~ CODE ~~~
from enum import IntEnum


class HorseVariantAndMarkings(IntEnum):
    WHITE = 0
    CREAMY = 1
    CHESTNUT = 2
    BROWN = 3
    BLACK = 4
    GRAY = 5
    DARKBROWN = 6
    WHITE_WITH_WHITESTOCKINGS = 256
    CREAMY_WITH_WHITESTOCKINGS = 257
    CHESTNUT_WITH_WHITESTOCKINGS = 258
    BROWN_WITH_WHITESTOCKINGS = 259
    BLACK_WITH_WHITESTOCKINGS = 260
    GRAY_WITH_WHITESTOCKINGS = 261
    DARKBROWN_WITH_WHITESTOCKINGS = 262
    WHITE_WITH_WHITEFIELD = 512
    CREAMY_WITH_WHITEFIELD = 513
    CHESTNUT_WITH_WHITEFIELD = 514
    BROWN_WITH_WHITEFIELD = 515
    BLACK_WITH_WHITEFIELD = 516
    GRAY_WITH_WHITEFIELD = 517
    DARKBROWN_WITH_WHITEFIELD = 518
    WHITE_WITH_WHITEDOTS = 768
    CREAMY_WITH_WHITEDOTS = 769
    CHESTNUT_WITH_WHITEDOTS = 770
    BROWN_WITH_WHITEDOTS = 771
    BLACK_WITH_WHITEDOTS = 772
    GRAY_WITH_WHITEDOTS = 773
    DARKBROWN_WITH_WHITEDOTS = 774
    WHITE_WITH_BLACK_DOTS = 1024
    CREAMY_WITH_BLACK_DOTS = 1025
    CHESTNUT_WITH_BLACK_DOTS = 1026
    BROWN_WITH_BLACK_DOTS = 1027
    BLACK_WITH_BLACK_DOTS = 1028
    GRAY_WITH_BLACK_DOTS = 1029
    DARKBROWN_WITH_BLACK_DOTS = 1030
