"""
Generated from symbols.json for ::java::data::dialog::action::DynamicCustomAction
Local link to file: vanilla_mcdoc/data/dialog/action/DynamicCustomAction.py
"""
# ~~~ CODE ~~~
from typing import TYPE_CHECKING, Annotated

from vanilla_mcdoc.base import GeneratedModel
from vanilla_mcdoc.minecraft_types import IdSpec

if TYPE_CHECKING:
    from vanilla_mcdoc.util.custom_event.UnknownDynamicAdditions import UnknownDynamicAdditions


class DynamicCustomAction(GeneratedModel):
    id: Annotated[str, IdSpec()]  # ID of a custom action. Has no functionality on vanilla servers.
    additions: UnknownDynamicAdditions | None = None  # Static fields added in addition to the fields generated by input.
